export default function Terms() {
  return (
    <div>
      <h1 className="text-h1" style={{ marginBottom: 16 }}>Terms of Service</h1>
      <div className="stack--md text-sm" style={{ color: 'var(--sand)', lineHeight: 1.7 }}>
        <p>NutriScan provides an AI-powered food scanning tool for informational and educational purposes only.</p>
        <h2 className="text-h3" style={{ color: 'var(--cream)', marginTop: 16 }}>1. Acceptance</h2>
        <p>By using NutriScan, you agree to these terms. If you do not agree, do not use the service.</p>
        <h2 className="text-h3" style={{ color: 'var(--cream)', marginTop: 16 }}>2. Not Medical Advice</h2>
        <p>NutriScan is not a medical device. Scores and analysis are generated by AI and may contain errors. Always consult a qualified healthcare professional for dietary advice.</p>
        <h2 className="text-h3" style={{ color: 'var(--cream)', marginTop: 16 }}>3. User Data</h2>
        <p>Scan data is stored securely and used only to improve your experience. See our Privacy Policy for details.</p>
        <h2 className="text-h3" style={{ color: 'var(--cream)', marginTop: 16 }}>4. Changes</h2>
        <p>We may update these terms at any time. Continued use after changes constitutes acceptance.</p>
        <p style={{ marginTop: 24, color: 'var(--muted)', fontSize: 12 }}>Last updated: July 2025</p>
      </div>
    </div>
  )
}
