declare module 'lucide-react' {
  import { ComponentType, SVGAttributes } from 'react'
  
  export type Icon = ComponentType<SVGAttributes<SVGSVGElement>>
  
  export interface LucideProps extends SVGAttributes<SVGSVGElement> {
    size?: number | string
    strokeWidth?: number | string
    absoluteStrokeWidth?: boolean
  }

  type ForwardRefComponent<T, P = {}> = ComponentType<P> & {
    displayName?: string
  }

  type IconComponent = ForwardRefComponent<SVGSVGElement, LucideProps>

  export const Scan: IconComponent
  export const ScanLine: IconComponent
  export const ScanBarcode: IconComponent
  export const ScanEye: IconComponent
  export const ScanFace: IconComponent
  export const ScanSearch: IconComponent
  export const ScanText: IconComponent
  export const RefreshCw: IconComponent
  export const ChevronRight: IconComponent
  export const Flame: IconComponent
  export const ZapOff: IconComponent
  export const CheckCircle2: IconComponent
  export const Target: IconComponent
  export const Award: IconComponent
  export const Camera: IconComponent
  export const Barcode: IconComponent
  export const Plus: IconComponent
  export const Minus: IconComponent
  export const X: IconComponent
  export const Check: IconComponent
  export const AlertTriangle: IconComponent
  export const Info: IconComponent
  export const Users: IconComponent
  export const UtensilsCrossed: IconComponent
  export const TrendingUp: IconComponent
  export const TrendingDown: IconComponent
  export const Scale: IconComponent
  export const Calendar: IconComponent
  export const Clock: IconComponent
  export const Star: IconComponent
  export const Heart: IconComponent
  export const Activity: IconComponent
  export const Zap: IconComponent
  export const Leaf: IconComponent
  export const Apple: IconComponent
  export const Wheat: IconComponent
  export const Milk: IconComponent
  export const Egg: IconComponent
  export const Fish: IconComponent
  export const Beef: IconComponent
  export const Drumstick: IconComponent
  export const Carrot: IconComponent
  export const Coffee: IconComponent
  export const Pizza: IconComponent
  export const Burger: IconComponent
  export const Candy: IconComponent
  export const Cookie: IconComponent
  export const Chocolate: IconComponent
  export const Utensils: IconComponent
  export const Home: IconComponent
  export const Settings: IconComponent
  export const LogOut: IconComponent
  export const User: IconComponent
  export const Search: IconComponent
  export const Menu: IconComponent
  export const ShoppingCart: IconComponent
  export const Package: IconComponent
  export const CreditCard: IconComponent
  export const ArrowLeft: IconComponent
  export const ArrowRight: IconComponent
  export const ChevronDown: IconComponent
  export const ChevronUp: IconComponent
  export const MoreVertical: IconComponent
  export const MoreHorizontal: IconComponent
  export const Filter: IconComponent
  export const SlidersHorizontal: IconComponent
  export const Grid: IconComponent
  export const List: IconComponent
  export const Save: IconComponent
  export const Edit: IconComponent
  export const Trash: IconComponent
  export const Share2: IconComponent
  export const Download: IconComponent
  export const Upload: IconComponent
  export const Printer: IconComponent
  export const ExternalLink: IconComponent
  export const Link: IconComponent
  export const Link2: IconComponent
  export const Copy: IconComponent
  export const Mail: IconComponent
  export const Phone: IconComponent
  export const MapPin: IconComponent
  export const Globe: IconComponent
  export const Cloud: IconComponent
  export const Wind: IconComponent
  export const Droplets: IconComponent
  export const Thermometer: IconComponent
  export const Sunrise: IconComponent
  export const Sunset: IconComponent
  export const Moon: IconComponent
  export const Sun: IconComponent
  export const CloudRain: IconComponent
  export const Snowflake: IconComponent
  export const Flashlight: IconComponent
  export const Cpu: IconComponent
  export const Wifi: IconComponent
  export const Bluetooth: IconComponent
  export const Speaker: IconComponent
  export const Music: IconComponent
  export const Headphones: IconComponent
  export const Mic: IconComponent
  export const Video: IconComponent
  export const Image: IconComponent
  export const Film: IconComponent
  export const Play: IconComponent
  export const Pause: IconComponent
  export const SkipBack: IconComponent
  export const SkipForward: IconComponent
  export const Repeat: IconComponent
  export const Shuffle: IconComponent
  export const Volume2: IconComponent
  export const VolumeX: IconComponent
  export const Maximize: IconComponent
  export const Minimize: IconComponent
  export const ZoomIn: IconComponent
  export const ZoomOut: IconComponent
  export const Move: IconComponent
  export const RotateCw: IconComponent
  export const RotateCcw: IconComponent
  export const FlipHorizontal: IconComponent
  export const FlipVertical: IconComponent
  export const Type: IconComponent
  export const Bold: IconComponent
  export const Italic: IconComponent
  export const Underline: IconComponent
  export const AlignLeft: IconComponent
  export const AlignCenter: IconComponent
  export const AlignRight: IconComponent
  export const AlignJustify: IconComponent
  export const ListOrdered: IconComponent
  export const ListBullet: IconComponent
  export const Quote: IconComponent
  export const Code: IconComponent
  export const Terminal: IconComponent
  export const Database: IconComponent
  export const Server: IconComponent
  export const HardDrive: IconComponent
  export const Folder: IconComponent
  export const FolderOpen: IconComponent
  export const File: IconComponent
  export const FileText: IconComponent
  export const FileImage: IconComponent
  export const Inbox: IconComponent
  export const Send: IconComponent
  export const MessageCircle: IconComponent
  export const MessageSquare: IconComponent
  export const Map: IconComponent
  export const Navigation: IconComponent
  export const Compass: IconComponent
  export const Anchor: IconComponent
  export const Car: IconComponent
  export const Truck: IconComponent
  export const Bike: IconComponent
  export const Bus: IconComponent
  export const Train: IconComponent
  export const Plane: IconComponent
  export const Rocket: IconComponent
  export const Waves: IconComponent
  export const Droplet: IconComponent
  export const FlaskConical: IconComponent
  export const Beaker: IconComponent
  export const Hexagon: IconComponent
  export const Square: IconComponent
  export const Circle: IconComponent
  export const Triangle: IconComponent
  export const Diamond: IconComponent
  export const Cross: IconComponent
  export const PlusCircle: IconComponent
  export const MinusCircle: IconComponent
  export const CheckCircle: IconComponent
  export const XCircle: IconComponent
  export const AlertCircle: IconComponent
  export const HelpCircle: IconComponent
  export const Ban: IconComponent
  export const Ghost: IconComponent
  export const Skull: IconComponent
  export const Trophy: IconComponent
  export const Medal: IconComponent
  export const Crown: IconComponent
  export const Gem: IconComponent
  export const Sparkles: IconComponent
  export const Smile: IconComponent
  export const Meh: IconComponent
  export const Frown: IconComponent
  export const Angry: IconComponent
  export const Fire: IconComponent
  export const Bomb: IconComponent
  export const Boom: IconComponent
  export const Gift: IconComponent
  export const Ticket: IconComponent
  export const Presentation: IconComponent
  export const Clapperboard: IconComponent
  export const Pipette: IconComponent
  export const Palette: IconComponent
  export const Paintbrush: IconComponent
  export const Pen: IconComponent
  export const PenTool: IconComponent
  export const Eraser: IconComponent
  export const Ruler: IconComponent
  export const Scissors: IconComponent
  export const Clipboard: IconComponent
  export const ClipboardCheck: IconComponent
  export const ClipboardList: IconComponent
  export const SignIn: IconComponent
  export const SignOut: IconComponent
  export const LogIn: IconComponent
  export const Key: IconComponent
  export const Keyboard: IconComponent
  export const Mouse: IconComponent
  export const MousePointer: IconComponent
  export const Smartphone: IconComponent
  export const Tablet: IconComponent
  export const Monitor: IconComponent
  export const Laptop: IconComponent
  export const Computer: IconComponent
  export const Casting: IconComponent
  export const Disc: IconComponent
  export const Radio: IconComponent
  export const Tv: IconComponent
  export const Timer: IconComponent
  export const TimerOff: IconComponent
  export const Hourglass: IconComponent
  export const AlarmClock: IconComponent
  export const Watch: IconComponent
  export const CalendarDays: IconComponent
  export const CalendarRange: IconComponent
  export const Notebook: IconComponent
  export const Undo: IconComponent
  export const Redo: IconComponent
  export const StepBack: IconComponent
  export const StepForward: IconComponent
  export const ArrowUp: IconComponent
  export const ArrowDown: IconComponent
  export const ChevronsUp: IconComponent
  export const ChevronsDown: IconComponent
  export const ChevronsLeft: IconComponent
  export const ChevronsRight: IconComponent
  export const CircleDashed: IconComponent
  export const CircleDot: IconComponent
  export const CircleEllipsis: IconComponent
  export const CircleSlash: IconComponent
  export const SquareDashed: IconComponent
  export const SquareDot: IconComponent
  export const SquareSlash: IconComponent
  export const Nut: IconComponent
  export const Cherry: IconComponent
  export const Citrus: IconComponent
  export const Salad: IconComponent
  export const CupSoda: IconComponent
  export const Wine: IconComponent
  export const Beer: IconComponent
  export const GlassWater: IconComponent
  export const IceCream: IconComponent
  export const Soup: IconComponent
  export const Bowl: IconComponent
  export const Pan: IconComponent
  export const Pot: IconComponent
  export const FryingPan: IconComponent
  export const Glass: IconComponent
  export const Cup: IconComponent
  export const Bottle: IconComponent
  export const Tea: IconComponent
  export const Bell: IconComponent
  export const BeerMug: IconComponent
  export const Champagne: IconComponent
  export const Croissant: IconComponent
  export const Bread: IconComponent
  export const Bagel: IconComponent
  export const Pancakes: IconComponent
  export const Waffle: IconComponent
  export const Doughnut: IconComponent
  export const Pretzel: IconComponent
  export const HotDog: IconComponent
  export const Taco: IconComponent
  export const Burrito: IconComponent
  export const Sandwich: IconComponent
  export const Wrap: IconComponent
  export const Dumpling: IconComponent
  export const FriedEgg: IconComponent
  export const Rice: IconComponent
  export const Sushi: IconComponent
  export const Salmon: IconComponent
  export const Shrimp: IconComponent
  export const Crab: IconComponent
  export const Lobster: IconComponent
  export const Squid: IconComponent
  export const Steak: IconComponent
  export const PoultryLeg: IconComponent
  export const Turkey: IconComponent
  export const Duck: IconComponent
  export const Lamb: IconComponent
  export const Goat: IconComponent
  export const Rabbit: IconComponent
  export const Venison: IconComponent
  export const Bone: IconComponent
  export const Jar: IconComponent
  export const Honey: IconComponent
  export const Cow: IconComponent
  export const Lettuce: IconComponent
  export const Cucumber: IconComponent
  export const Tomato: IconComponent
  export const Potato: IconComponent
  export const Corn: IconComponent
  export const Onion: IconComponent
  export const Garlic: IconComponent
  export const Ginger: IconComponent
  export const Chili: IconComponent
  export const Pepper: IconComponent
  export const Mushroom: IconComponent
  export const Peanuts: IconComponent
  export const Walnut: IconComponent
  export const Almond: IconComponent
  export const Cashew: IconComponent
  export const Seed: IconComponent
  export const Sesame: IconComponent
  export const Pumpkin: IconComponent
  export const Acorn: IconComponent
  export const Leaves: IconComponent
  export const Herb: IconComponent
  export const Clover: IconComponent
  export const TreeDeciduous: IconComponent
  export const TreeEvergreen: IconComponent
  export const PalmTree: IconComponent
  export const Cactus: IconComponent
  export const Pinecone: IconComponent
  export const Flower: IconComponent
  export const Flower2: IconComponent
  export const Tulip: IconComponent
  export const Rose: IconComponent
  export const Sunflower: IconComponent
  export const Blossom: IconComponent
  export const CherryBlossom: IconComponent
  export const Sprout: IconComponent
  export const Evergreen: IconComponent
  export const Tent: IconComponent
  export const Cave: IconComponent
  export const Dome: IconComponent
  export const Factory: IconComponent
  export const House: IconComponent
  export const Building: IconComponent
  export const Building2: IconComponent
  export const Bank: IconComponent
  export const Church: IconComponent
  export const Mosque: IconComponent
  export const Temple: IconComponent
  export const Castle: IconComponent
  export const Palace: IconComponent
  export const Store: IconComponent
  export const Shop: IconComponent
  export const Warehouse: IconComponent
  export const Greenhouse: IconComponent
  export const Storefront: IconComponent
  export const TentIcon: IconComponent
  export const Volcano: IconComponent
  export const Mountain: IconComponent
  export const Beach: IconComponent
  export const Island: IconComponent
  export const Desert: IconComponent
  export const Forest: IconComponent
  export const Park: IconComponent
  export const Field: IconComponent
  export const Farm: IconComponent
  export const Tractor: IconComponent
  export const SprayCan: IconComponent
  export const Plow: IconComponent
  export const Banana: IconComponent
  export const Grape: IconComponent
  export const Grapes: IconComponent
  export const Watermelon: IconComponent
  export const Peach: IconComponent
  export const Pear: IconComponent
  export const Avocado: IconComponent
  export const Pineapple: IconComponent
  export const Mango: IconComponent
  export const Pomegranate: IconComponent
  export const Fig: IconComponent
  export const Kiwi: IconComponent
  export const Papaya: IconComponent
  export const Lychee: IconComponent
  export const SunIcon: IconComponent
  export const MoonIcon: IconComponent
  export const CloudIcon: IconComponent
  export const CloudSnow: IconComponent
  export const CloudLightning: IconComponent
  export const CloudFog: IconComponent
  export const CloudHail: IconComponent
  export const Umbrella: IconComponent
  export const WindIcon: IconComponent
  export const Fan: IconComponent
  export const AirConditioner: IconComponent
  export const Fireplace: IconComponent
  export const Radiator: IconComponent
  export const Stove: IconComponent
  export const ThermometerSun: IconComponent
  export const ThermometerSnowflake: IconComponent
  export const Water: IconComponent
  export const Pool: IconComponent
  export const Bath: IconComponent
  export const Shower: IconComponent
  export const Hose: IconComponent
  export const Sprinkler: IconComponent
  export const Faucet: IconComponent
  export const Bucket: IconComponent
  export const Cupboard: IconComponent
  export const Sofa: IconComponent
  export const Armchair: IconComponent
  export const Bed: IconComponent
  export const BedDouble: IconComponent
  export const BedSingle: IconComponent
  export const Lamp: IconComponent
  export const LampFloor: IconComponent
  export const LampWall: IconComponent
  export const LampTable: IconComponent
  export const Lightbulb: IconComponent
  export const SpotLight: LucideIcon
  export const CeilingLight: LucideIcon
  export const Chandelier: LucideIcon
  export const Sconce: LucideIcon
  export const Torch: LucideIcon
  export const Lantern: LucideIcon
  export const Candle: LucideIcon
  export const Campfire: LucideIcon
  export const Firewood: LucideIcon
  export const Plug: LucideIcon
  export const Socket: LucideIcon
  export const Power: LucideIcon
  export const Battery: LucideIcon
  export const BatteryCharging: LucideIcon
  export const BatteryFull: LucideIcon
  export const BatteryLow: LucideIcon
  export const BatteryMedium: LucideIcon
  export const SolarPanel: LucideIcon
  export const WindTurbine: LucideIcon
  export const HydroPower: LucideIcon
  export const Cable: LucideIcon
  export const HDMI: LucideIcon
  export const USB: LucideIcon
  export const WifiOff: LucideIcon
  export const RSS: LucideIcon
  export const Cast: LucideIcon
  export const Airplay: LucideIcon
  export const Gamepad: LucideIcon
  export const Joystick: LucideIcon
  export const Radar: LucideIcon
  export const GPS: LucideIcon
  export const Route: LucideIcon
  export const Crosshair: LucideIcon
  export const Locate: LucideIcon
  export const MapPinCheck: LucideIcon
  export const MapPinX: LucideIcon
  export const MapPinPlus: LucideIcon
  export const MapPinMinus: LucideIcon
  export const Pin: LucideIcon
  export const PushPin: LucideIcon
  export const Flag: LucideIcon
  export const Bookmark: LucideIcon
  export const Book: LucideIcon
  export const BookOpen: LucideIcon
  export const BookMarked: LucideIcon
  export const Library: LucideIcon
  export const GraduationCap: LucideIcon
  export const School: LucideIcon
  export const Academy: LucideIcon
  export const Brain: LucideIcon
  export const Idea: LucideIcon
  export const Genius: LucideIcon
  export const MentalHealth: LucideIcon
  export const Pill: LucideIcon
  export const Capsule: LucideIcon
  export const Syringe: LucideIcon
  export const Stethoscope: LucideIcon
  export const HeartPulse: LucideIcon
  export const Pulse: LucideIcon
  export const HeartHandshake: LucideIcon
  export const Lungs: LucideIcon
  export const Kidney: LucideIcon
  export const Liver: LucideIcon
  export const Muscle: LucideIcon
  export const Teeth: LucideIcon
  export const Tooth: LucideIcon
  export const Eye: LucideIcon
  export const Glasses: LucideIcon
  export const Sunglasses: LucideIcon
  export const Contact: LucideIcon
  export const Earbuds: LucideIcon
  export const Ear: LucideIcon
  export const Nose: LucideIcon
  export const Footprints: LucideIcon
  export const Hand: LucideIcon
  export const HandMetal: LucideIcon
  export const HandRight: LucideIcon
  export const HandLeft: LucideIcon
  export const HandIndex: LucideIcon
  export const HandGrab: LucideIcon
  export const HandPeace: LucideIcon
  export const HandHeart: LucideIcon
  export const HandHelping: LucideIcon
  export const HandHolding: LucideIcon
  export const HandWash: LucideIcon
  export const HandSoap: LucideIcon
  export const PawPrint: LucideIcon
  export const Bug: LucideIcon
  export const Beetle: LucideIcon
  export const Butterfly: LucideIcon
  export const Spider: LucideIcon
  export const Worm: LucideIcon
  export const Ant: LucideIcon
  export const Bee: LucideIcon
  export const Cricket: LucideIcon
  export const Mosquito: LucideIcon
  export const Scorpion: LucideIcon
  export const Snake: LucideIcon
  export const Turtle: LucideIcon
  export const Frog: LucideIcon
  export const Lizard: LucideIcon
  export const Crocodile: LucideIcon
  export const Dino: LucideIcon
  export const Cat: LucideIcon
  export const Dog: LucideIcon
  export const Bird: LucideIcon
  export const Eagle: LucideIcon
  export const Dove: LucideIcon
  export const Owl: LucideIcon
  export const Bat: LucideIcon
  export const Penguin: LucideIcon
  export const Parrot: LucideIcon
  export const Peacock: LucideIcon
  export const Swan: LucideIcon
  export const Flamingo: LucideIcon
  export const Feather: LucideIcon
  export const Whale: LucideIcon
  export const Shark: LucideIcon
  export const Dolphin: LucideIcon
  export const Octopus: LucideIcon
  export const Seahorse: LucideIcon
  export const Jellyfish: LucideIcon
  export const Shell: LucideIcon
  export const Spiral: LucideIcon
  export const Orbit: LucideIcon
  export const Meteor: LucideIcon
  export const MoonStar: LucideIcon
  export const MoonStars: LucideIcon
  export const Twilight: LucideIcon
  export const Night: LucideIcon
  export const CloudMoon: LucideIcon
  export const CloudSun: LucideIcon
  export const CloudDrizzle: LucideIcon
  export const Shield: LucideIcon
  export const Baby: LucideIcon
  export const ShoppingBag: LucideIcon
  export const GraduationCap: LucideIcon
  export const School: LucideIcon
  export const Academy: LucideIcon
  export const Brain: LucideIcon
  export const Idea: LucideIcon
  export const Genius: LucideIcon
  export const MentalHealth: LucideIcon
  export const Pill: LucideIcon
  export const Capsule: LucideIcon
  export const Syringe: LucideIcon
  export const Stethoscope: LucideIcon
  export const HeartPulse: LucideIcon
  export const Pulse: LucideIcon
  export const HeartHandshake: LucideIcon
  export const Lungs: LucideIcon
  export const Kidney: LucideIcon
  export const Liver: LucideIcon
  export const Muscle: LucideIcon
  export const Teeth: LucideIcon
  export const Tooth: LucideIcon
  export const Eye: LucideIcon
  export const Glasses: LucideIcon
  export const Sunglasses: LucideIcon
  export const Contact: LucideIcon
  export const Earbuds: LucideIcon
  export const Ear: LucideIcon
  export const Nose: LucideIcon
  export const Footprints: LucideIcon
  export const Hand: LucideIcon
  export const HandMetal: LucideIcon
  export const HandRight: LucideIcon
  export const HandLeft: LucideIcon
  export const HandIndex: LucideIcon
  export const HandGrab: LucideIcon
  export const HandPeace: LucideIcon
  export const HandHeart: LucideIcon
  export const HandHelping: LucideIcon
  export const HandHolding: LucideIcon
  export const HandWash: LucideIcon
  export const HandSoap: LucideIcon
  export const PawPrint: LucideIcon
  export const Bug: LucideIcon
  export const Beetle: LucideIcon
  export const Butterfly: LucideIcon
  export const Spider: LucideIcon
  export const Worm: LucideIcon
  export const Ant: LucideIcon
  export const Bee: LucideIcon
  export const Cricket: LucideIcon
  export const Mosquito: LucideIcon
  export const Scorpion: LucideIcon
  export const Snake: LucideIcon
  export const Turtle: LucideIcon
  export const Frog: LucideIcon
  export const Lizard: LucideIcon
  export const Crocodile: LucideIcon
  export const Dino: LucideIcon
  export const Cat: LucideIcon
  export const Dog: LucideIcon
  export const Bird: LucideIcon
  export const Eagle: LucideIcon
  export const Dove: LucideIcon
  export const Owl: LucideIcon
  export const Bat: LucideIcon
  export const Penguin: LucideIcon
  export const Parrot: LucideIcon
  export const Peacock: LucideIcon
  export const Swan: LucideIcon
  export const Flamingo: LucideIcon
  export const Feather: LucideIcon
  export const Whale: LucideIcon
  export const Shark: LucideIcon
  export const Dolphin: LucideIcon
  export const Octopus: LucideIcon
  export const Seahorse: LucideIcon
  export const Jellyfish: LucideIcon
  export const Shell: LucideIcon
  export const Spiral: LucideIcon
  export const Orbit: LucideIcon
  export const Meteor: LucideIcon
  export const MoonStar: LucideIcon
  export const MoonStars: LucideIcon
  export const Twilight: LucideIcon
  export const Night: LucideIcon
  export const CloudMoon: LucideIcon
  export const CloudSun: LucideIcon
  export const CloudDrizzle: LucideIcon
}