export default function TermsOfService() {
  return (
    <div className="max-w-2xl mx-auto px-4 py-12 prose dark:prose-invert">
      <h1>Terms of Service</h1>
      <p><strong>Last updated:</strong> {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
 
      <h2>1. Acceptance</h2>
      <p>By using HealthOX, you agree to these terms. If you do not agree, do not use the app.</p>
 
      <h2>2. What HealthOX Is</h2>
      <p>HealthOX is an AI-powered food health information tool. It provides health ratings and ingredient analysis for educational purposes. It is NOT a medical device or medical service.</p>
 
      <h2>3. Health Disclaimer — Please Read</h2>
      <p>The health scores, ingredient warnings, and consumption recommendations provided by HealthOX are generated by AI and are for general informational purposes only. They:</p>
      <ul>
        <li>Are NOT a substitute for professional medical or nutritional advice</li>
        <li>May contain errors or inaccuracies</li>
        <li>Should NOT be used to make medical decisions</li>
        <li>Are based on publicly available nutritional data which may not always be accurate</li>
      </ul>
      <p>Always consult a qualified healthcare professional before making dietary changes, especially if you have diabetes, high blood pressure, or other health conditions.</p>
 
      <h2>4. User Responsibilities</h2>
      <ul>
        <li>You are responsible for the accuracy of your health profile information</li>
        <li>You must be 13 years or older to use this app</li>
        <li>Do not misuse or attempt to abuse the AI analysis system</li>
      </ul>
 
      <h2>5. Limitation of Liability</h2>
      <p>HealthOX is provided "as is." We are not liable for any health decisions made based on our AI analysis. Use at your own discretion.</p>
 
      <h2>6. Intellectual Property</h2>
      <p>The HealthOX app, its design, and codebase are owned by the HealthOX team. Product data is sourced from Open Food Facts (ODbL license) and other public sources.</p>
 
      <h2>7. Changes to Terms</h2>
      <p>We may update these terms. Continued use of the app means you accept the updated terms.</p>
 
      <h2>8. Contact</h2>
      <p>Questions: healthox.app@gmail.com</p>
    </div>
  )
}