export default function Disclaimer() {
  return (
    <div>
      <h1 className="text-h1" style={{ marginBottom: 16 }}>Disclaimer</h1>
      <div className="stack--md text-sm" style={{ color: 'var(--sand)', lineHeight: 1.7 }}>
        <p><strong>NutriScan is not a medical device and is not intended to diagnose, treat, cure, or prevent any disease.</strong></p>
        <p style={{ marginTop: 16 }}>Health scores and ingredient analysis are generated by artificial intelligence and automated algorithms. They may contain inaccuracies, errors, or omissions. Scores are relative and should not be used as the sole basis for dietary decisions.</p>
        <h2 className="text-h3" style={{ color: 'var(--cream)', marginTop: 16 }}>No Professional Advice</h2>
        <p>The information provided by NutriScan is for general informational purposes only. It does not constitute medical, nutritional, or dietary advice. Always consult a qualified healthcare professional or registered dietitian before making changes to your diet.</p>
        <h2 className="text-h3" style={{ color: 'var(--cream)', marginTop: 16 }}>Data Accuracy</h2>
        <p>Product data is sourced from OpenFoodFacts, brand websites, and user contributions. We do not guarantee the accuracy, completeness, or timeliness of any product information. Ingredient lists and nutritional values may change without notice.</p>
        <h2 className="text-h3" style={{ color: 'var(--cream)', marginTop: 16 }}>FSSAI Compliance</h2>
        <p>References to FSSAI regulations are based on published FSSAI standards. We recommend verifying compliance directly with the latest FSSAI publications for authoritative guidance.</p>
        <h2 className="text-h3" style={{ color: 'var(--cream)', marginTop: 16 }}>Limitation of Liability</h2>
        <p>NutriScan and its creators shall not be liable for any damages arising from the use of, or inability to use, this application. Use at your own risk.</p>
        <p style={{ marginTop: 24, color: 'var(--muted)', fontSize: 12 }}>Last updated: July 2025</p>
      </div>
    </div>
  )
}
