import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Medical Disclaimer | HealthOX',
  description: 'Important medical disclaimer - HealthOX is not a substitute for professional medical advice.',
}

export default function DisclaimerPage() {
  return (
    <>
      <h1 className="text-3xl font-black text-white mb-2">Medical Disclaimer</h1>
      <p className="text-sm text-[#7a8fa6] mb-8">Last updated: May 2026</p>

      <div className="space-y-6 text-sm text-[#c8d6e0] leading-relaxed">
        <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl">
          <p className="font-bold text-red-400 text-base">⚠️ Not Medical Advice</p>
          <p className="mt-2 text-[#f0f4f8]">
            HealthOX provides food analysis, health scores, and ingredient information 
            for informational and educational purposes only. The content on this app 
            is not intended to be a substitute for professional medical advice, 
            diagnosis, or treatment.
          </p>
        </div>

        <Section title="No Doctor-Patient Relationship">
          <p>
            Use of HealthOX does not create a doctor-patient relationship between you 
            and the app operator. The AI-powered analysis and health scores are 
            generated by algorithms and should not be considered as medical opinions.
          </p>
        </Section>

        <Section title="Algorithm Limitations">
          <p>
            Our AI analysis (powered by Groq) and health scoring engine have limitations:
          </p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>They may not detect all potentially harmful ingredients</li>
            <li>They may incorrectly flag safe ingredients as harmful</li>
            <li>They do not account for individual medical history beyond what you provide</li>
            <li>They cannot predict allergic reactions or individual sensitivities</li>
          </ul>
        </Section>

        <Section title="Always Consult a Professional">
          <p>
            Before making any changes to your diet, especially if you have a medical 
            condition such as diabetes, high blood pressure, heart disease, or 
            food allergies, consult a qualified healthcare professional, registered 
            dietitian, or your primary care physician.
          </p>
        </Section>

        <Section title="Emergency Situations">
          <p className="font-bold text-amber-400">
            HealthOX is NOT for emergency medical situations. If you suspect a food 
            allergy reaction, food poisoning, or any medical emergency, call your 
            local emergency services immediately.
          </p>
        </Section>

        <Section title="Data Accuracy">
          <p>
            Product data is sourced from Open Food Facts, a community-maintained 
            database, and may contain inaccuracies. Ingredient lists and nutritional 
            information may not reflect the latest product formulation. Always check 
            the physical product label for the most accurate information.
          </p>
        </Section>

        <Section title="FSSAI Compliance Information">
          <p>
            HealthOX references FSSAI (Food Safety and Standards Authority of India) 
            guidelines where applicable. However, compliance indicators shown in the 
            app are algorithm-generated and should not be considered as official 
            FSSAI certification or approval.
          </p>
        </Section>

        <Section title="Reliance on Information & Limitation of Liability">
          <p>
            Reliance on any information provided by HealthOX is solely at your own 
            risk. To the maximum extent permitted by applicable law, including the 
            Information Technology Act, 2000, the app operator, Samad Saifi, and 
            HealthOX disclaim all liability for any damages or losses resulting from 
            use of the app.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            For questions about this disclaimer, contact:
          </p>
          <p className="mt-1 text-emerald-400">
            Samad Saifi<br />
            samadlylives00@gmail.com
          </p>
        </Section>
      </div>
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-base font-bold text-white mb-2">{title}</h2>
      <div className="text-sm text-[#c8d6e0] leading-relaxed">{children}</div>
    </div>
  )
}
